version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_USER=postgres
      - DB_PASS=suhas
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=employee_management
    depends_on:
      database:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: suhas
      POSTGRES_DB: employee_management
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d employee_management"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
