CREATE TABLE employees (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  employee_id VARCHAR(10) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(10) NOT NULL,
  department VARCHAR(50) NOT NULL,
  date_Of_joining DATE NOT NULL,
  role VARCHAR(50) NOT NULL
);
